# This is an appspec.yml template file for use with an Amazon ECS deployment in CodeDeploy.
# For help completing this file, see the "AppSpec File Reference" in the  
#   "CodeDeploy User Guide" at
#   https://docs.aws.amazon.com/codedeploy/latest/userguide/app-spec-ref.html
version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:349396007468:task-definition/task-poc-app"
        LoadBalancerInfo: 
          ContainerName: "poc-app" # Specify the name of your Amazon ECS application's container
          ContainerPort: "3000" # Specify the port for your container where traffic reroutes 
# Optional properties
        PlatformVersion: "LATEST" # Specify the version of your Amazon ECS Service
#Hooks:
# # Hooks for Amazon ECS deployments are:
#     - BeforeInstall: "" # Specify a Lambda function name or ARN
#     - AfterInstall: "" # Specify a Lambda function name or ARN
#     - AfterAllowTestTraffic: "" # Specify a Lambda function name or ARN
#     - BeforeAllowTraffic: "" # Specify a Lambda function name or ARN
#     - AfterAllowTraffic: "" # Specify a Lambda function name or ARN