version: 0.2

env:
  exported-variables:
    - BuildID
    - BuildTag
    - Region

phases:
  build:
    commands:
      - cd terraform/
      - terraform init
      - terraform plan
      - "export BuildID=`echo $CODEBUILD_BUILD_ID | cut -d: -f1`"
      - "export BuildTag=`echo $CODEBUILD_BUILD_ID | cut -d: -f2`"
      - "export Region=$AWS_REGION"
      - "echo $"