metadata:
  created: '2022-04-05T19:14:37.559000-03:00'
  pipelineArn: arn:aws:codepipeline:us-east-1:652839185683:pipeline-sample-app
  updated: '2022-04-06T18:39:56.697000-03:00'
pipeline:
  artifactStore:
    location: terraform-backend-demo-fsavoia
    type: S3
  name: pipeline-sample-app
  roleArn: arn:aws:iam::652839185683:role/service-role/AWSCodePipelineServiceRole-us-east-1-pipeline-sample-app
  stages:
  - actions:
    - actionTypeId:
        category: Source
        owner: AWS
        provider: S3
        version: '1'
      configuration:
        PollForSourceChanges: 'false'
        S3Bucket: terraform-backend-demo-fsavoia
        S3ObjectKey: sample-app.zip
      inputArtifacts: []
      name: Source
      namespace: SourceVariables
      outputArtifacts:
      - name: SourceArtifact
      region: us-east-1
      runOrder: 1
    name: Source
  - actions:
    - actionTypeId:
        category: Build
        owner: AWS
        provider: CodeBuild
        version: '1'
      configuration:
        ProjectName: tfsec
      inputArtifacts:
      - name: SourceArtifact
      name: tfec_security
      namespace: TFSEC
      outputArtifacts: []
      region: us-east-1
      runOrder: 1
    name: tfsec_check
  - actions:
    - actionTypeId:
        category: Approval
        owner: AWS
        provider: Manual
        version: '1'
      configuration:
        CustomData: 'tfsec errors found: #{TFSEC.checks_failed}'
        ExternalEntityLink: https://#{TFSEC.Region}.console.aws.amazon.com/codesuite/codebuild/652839185683/projects/#{TFSEC.BuildID}/build/#{TFSEC.BuildID}%3A#{TFSEC.BuildTag}/?region=#{TFSEC.Region}
      inputArtifacts: []
      name: Terraform_Security_Analysis_Manual_Review
      outputArtifacts: []
      region: us-east-1
      runOrder: 1
    name: Terraform_Security
  - actions:
    - actionTypeId:
        category: Build
        owner: AWS
        provider: CodeBuild
        version: '1'
      configuration:
        ProjectName: terraform_plan
      inputArtifacts:
      - name: SourceArtifact
      name: Terraform_Plan
      namespace: TERRAFORM
      outputArtifacts: []
      region: us-east-1
      runOrder: 1
    name: Terraform_Plan
  - actions:
    - actionTypeId:
        category: Approval
        owner: AWS
        provider: Manual
        version: '1'
      configuration:
        CustomData: Terraform plan review
        ExternalEntityLink: https://#{TERRAFORM.Region}.console.aws.amazon.com/codesuite/codebuild/652839185683/projects/#{TERRAFORM.BuildID}/build/#{TERRAFORM.BuildID}%3A#{TERRAFORM.BuildTag}/?region=#{TERRAFORM.Region}
      inputArtifacts: []
      name: Terraform_Plan_Manual_Review
      outputArtifacts: []
      region: us-east-1
      runOrder: 1
    name: Terraform_Plan_Manual_Review
  - actions:
    - actionTypeId:
        category: Build
        owner: AWS
        provider: CodeBuild
        version: '1'
      configuration:
        ProjectName: terraform_apply
      inputArtifacts:
      - name: SourceArtifact
      name: Terraform_Apply
      outputArtifacts: []
      region: us-east-1
      runOrder: 1
    name: Terraform_Apply
  - actions:
    - actionTypeId:
        category: Approval
        owner: AWS
        provider: Manual
        version: '1'
      configuration:
        CustomData: Do you want to deploy application pro Prod?
      inputArtifacts: []
      name: DeployToProd
      outputArtifacts: []
      region: us-east-1
      runOrder: 1
    - actionTypeId:
        category: Deploy
        owner: AWS
        provider: CodeDeploy
        version: '1'
      configuration:
        ApplicationName: AppECS-awslabs-sample-svc-sample-app
        DeploymentGroupName: DgpECS-awslabs-sample-svc-sample-app
      inputArtifacts:
      - name: SourceArtifact
      name: Deploy
      namespace: DeployVariables
      outputArtifacts: []
      region: us-east-1
      runOrder: 2
    name: Deploy
  version: 25
